// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testSE01', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testSE01', async function() {
    // Test name: testSE01
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1064x816 | 
    await driver.manage().window().setRect({ width: 1064, height: 816 })
    // 3 | click | css=input:nth-child(1) | 
    await driver.findElement(By.css("input:nth-child(1)")).click()
    // 4 | type | css=input:nth-child(1) | Achraf
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys("Achraf")
    // 5 | sendKeys | css=input:nth-child(1) | ${KEY_ENTER}
    await driver.findElement(By.css("input:nth-child(1)")).sendKeys(Key.ENTER)
    // 6 | assertAlert | submitted successfully ! | 
    assert(await driver.switchTo().alert().getText() == "submitted successfully !")
    // 7 | click | css=html | 
    await driver.findElement(By.css("html")).click()
  })
})
